### ISSUE TITLE
LIRR M7

### ISSUE THREAD

**Issue by TruBluLew** [DerJantob/TSW2_Controller#19]
Sorry, didn't mean to keep commenting on Youtube. Figured I should post here :P

My last comment was as follows:

Can confirm buttons are working again! And I had my profile working for the LIRR M7 too for a few minutes. The problem I'm having is when JoyZ is in a certain position, the throttle or brake keeps changing variables, even when the program is showing my JoyZ to be in one position. Do you have any idea why that may be? 

For example, JoyZ can be at -37 for 37% brakes. But it'll jump to 74% brake, then Max Brake, then back down to 74%, and repeat. I used similar Joy States and Special cases as you did on the BR423 since that has a Master Controller too but I'm at a loss.

Joy States: 1|9=10 95|100=95 -9|-1=-10 -100|-96=-95
Time Factor: 49|48
Long Press: 0|10:350 -10|0:350
Special Cases: Coast=0 Min_Power=10 Max_Power=95 Min_Brake=-10 Max_Brake=-95 Emergency=-100
[Trainconfig.csv](https://github.com/DerJantob/TSW2_Controller/files/8300562/Trainconfig.csv)

**Comment by DerJantob** [comment]
This is not a bug on your part, but a bug in the program. These text indicators are somehow structured differently for each train. I'll have to see how to fix that.

**Comment by DerJantob** [comment]
Ok, I think I found the problem. 
Could you maybe try in advance if it works with the following version?
[TSW2_Controller_UpdateBeta.zip](https://github.com/DerJantob/TSW2_Controller/files/8309605/TSW2_Controller_UpdateBeta.zip)
You wrote that you entered 49|48 as the time factor, but in the file you sent along it says something different. You should perhaps check this again.

**Comment by TruBluLew** [comment]
I'm pretty sure you found the problem. So far it's working perfectly! Thank you so much for taking time out your day to fix this. I know you have other life stuff to do so I really do appreciate this. I'm gonna work on the other MTA trains and I'll send you everything in a text file when I'm finished to add to your program.

**Comment by DerJantob** [comment]
Glad to hear it's working for you, and thanks for the praise! :)  
I'm creating the public update now.
It's also nice of you to send me your config, but I'll have to see to what extent I can implement that, because depending on the game language (and joystick) it won't work for one.

**Comment by TruBluLew** [comment]
No worries at all! I use the same joystick you use but I have noticed that sometimes the english language and german language games seem to differ slightly. I also think there may be 1 more very small bug in the program. When you activate a profile and you move JoyZ for the first time, the program seems to input "d" every few seconds. Not sure if that's intentional or not. Other than that, I'm having an amazing time with your program and adding more trains to work with it has been really fun! :D

[Trainconfig.csv](https://github.com/DerJantob/TSW2_Controller/files/8328162/Trainconfig.csv)

**Comment by DerJantob** [comment]
Yes, I have noticed the problem as well. The program behaves strangely for a short time after starting. I'll have to see how to fix that. But for now, it doesn't bother too much.
