### ISSUE TITLE
BR403 - Joystick position mismatch Controls Window vs TSW2_Controller window

### ISSUE THREAD

**Issue by danbaz101** [DerJantob/TSW2_Controller#21]
Hi Jannik,

After having some good runs with BR442 and BR422 I thought to setup my joysticks for the BR403.

In the Controls window I have selected "Inverted" and "Other Joy-Mode" so that with the joystick in the forward position it shows zero in the joystick summary in the top right corner (actually it dissappears altogether). When moving the joystick all the way to the aft position, the emergency brake position, the reading is 100. So this is all good.
Now when I save and go back to the main TSW2_Controller window and I select Joystick 1 and I move the joystick, it moves from forward to aft, from 50 to 0, so the opposite numbering and only half the range.

Hope you can help me.

Joystick in middle position:
![220320 BR403_Joy1_AxisZ](https://user-images.githubusercontent.com/83304085/159171441-77a02691-b895-4ace-bd9a-26629c983c0e.png)

Joystick almost in full forward position (release)
![220320 BR403_Joy1_AxisZ_2](https://user-images.githubusercontent.com/83304085/159171537-67de925c-4d14-42cd-8b1b-7033daa7bcfa.png)

**Comment by DerJantob** [comment]
I haven't really tried much with multiple joysticks because unfortunately I only own one. I just noticed the bug that the "Inverted" and "Other Joy-Mode" affects all joysticks, not just the one with the selected number. I will have to fix that. So, is it possible that you are using JoyZ of Joystick 0 for the throttle?

**Comment by danbaz101** [comment]
Yes, correct. I am using Joystick 0 JoyZ for the throttle.

**Comment by DerJantob** [comment]
Ok, I think I found the problem.
Could you maybe try in advance if it works with the following version?
[TSW2_Controller_PreRelease_1_1.0.4.zip](https://github.com/DerJantob/TSW2_Controller/files/8318897/TSW2_Controller_PreRelease_1_1.0.4.zip)

**Comment by danbaz101** [comment]
Great.
I have tried it. It works OK now. The reading in both windows is now the same. Nice! :)

However the brake handle does not behave yet as it should, but perhaps that is a settings error.
Applying the brake a first time works fine, but then releasing the brake, moving the handle back forward does not work.

When I applied full braking that was OK, but when I then set the handle back at 50% the lever stayed in the full braking position.

This is what I have in the config csv file:
BR403/406,Bremse,1,JoyZ,1,1,,Bremse,,Stufen,9,[14=1][Release=0][Bypass=0][1A=1][1B=2][2=3][3=4][4=5][5=6][6=7][7=8][Full Application=9][Full/Application=9],335,
There is also a default line for the bypass. Assume that one does not bite...?

Thanks for your quick help. Pls do not let this get in the way of studying! :)
I can wait.

Have I made an error in this?

**Comment by DerJantob** [comment]
For me, it works with your settings. Could you maybe send me the whole TrainConfig.csv?

**Comment by danbaz101** [comment]
Sure. Here you are.

[Trainconfig.csv](https://github.com/DerJantob/TSW2_Controller/files/8326945/Trainconfig.csv)

**Comment by danbaz101** [comment]
I have tried to do this, but it did not solve my problem.
When I move the joystick handle down, the train lever goes down, when I move the joystick handle back up, the train lever stays where it was, when I then move the joystick lever down again the train lever moves further down. So in the end my joystick handle is in up position, but the train is in emergency brakes..

The reading in the app is wrong too. It states that the brake is in 1 and should be in 1. The scan results show something like brake is off, but the train lever is in emergency brake position. So there is a disconnect that is not recognized by the error handling yet.

Looking forward to hearing from you.

**Comment by DerJantob** [comment]
I am unfortunately still not able to reproduce your problem. Can you send me maybe your user.config file, located in the folder next to your TrainConfig? (TSW2_Controller.exe_URL_[other stuff]/1.0.3.1/user.config)

**Comment by danbaz101** [comment]
Sure. Here you are.

I had to zip it as .config files were not accepted.
[user.zip](https://github.com/DerJantob/TSW2_Controller/files/8358156/user.zip)

**Comment by DerJantob** [comment]
Hm, I can not see a direct problem with this either.
But I still have a few questions:
1. Does this problem only occur on the prerelease version or also on the version 1.0.3?
2. Does the lever not move at all, or only a little?
3. When you click on a text box, do the correct buttons get pressed or does nothing happen here either?

**Comment by danbaz101** [comment]
Hi Jannik,

1. I am on pre release 1 V 1.0.4
2. The lever only moves one way, in the direction of applying more brake.
3. I am not sure what you mean by this...sorry. Pls can you explain or show?

I have made another video.
In this I slowly add brake until 50%, then go back up. Then I apply brake again until full brake and at last I move my joystick all the to zero again. You will see that the lever in the sim will move only in one direction. Hope it helps.

https://youtu.be/wd7_EiIM0XQ

**Comment by DerJantob** [comment]
After testing a lot, I think the problem is due to the different keyboard layouts. I have temporarily changed this for you to see if this fixes the problem. If not, then please tell me which keyboard layout / language you are using.
[TSW2_Controller_PreRelease_2_1.0.4.zip](https://github.com/DerJantob/TSW2_Controller/files/8402892/TSW2_Controller_PreRelease_2_1.0.4.zip)

Kind regards,
Jannik

**Comment by danbaz101** [comment]
Thanks a lot Jannik,

This has solved the problem. The brake handle is moving in both directions now.

There are my keyboard settings. i have a QWERTY keyboard.
![Schermafbeelding 2022-04-03 162945](https://user-images.githubusercontent.com/83304085/161432935-f79e1bb7-b4e7-4406-bb44-8abf1b58d885.png)

![Schermafbeelding 2022-04-03 163548](https://user-images.githubusercontent.com/83304085/161433174-30cd288c-946e-44a3-8ccd-ca2017e3cee0.png)


Kind regards,

Daniel

**Comment by DerJantob** [comment]
Thanks for the help and for testing!

**Comment by danbaz101** [comment]
Hi Jannik,
I saw the new version in the app and have installed it.
Now the brake handle does not work anymore.

Just letting you know.

I will try to install the version you gave me above again.

Kind regards,

Daniel

**Comment by DerJantob** [comment]
Have you changed your keys in the new setting?
![grafik](https://user-images.githubusercontent.com/79801484/162578884-02d31220-0bd4-4c07-986c-98bcf4e38aca.png)

**Comment by danbaz101** [comment]
Of course not.. :)

Done now. So I am on latest version now. It moves in the right direction again.

For some reason it keeps pressing my ; key for decreasing brake. Pls see new movie.

https://youtu.be/DqD34SQuN5o
Beginning: Joystick in full up. It keeps pressing ; and hence it shows Bypass.
After this  I moved joystick to the middle. Brake lever moved in the right direction, but then went back to Bypass
Then I moved joystick to full brake. Same happened.
I have not modified the settings on my end.

Sorry, I have all these issues.... 

Kind regards,

Daniel

**Comment by DerJantob** [comment]
Don't be sorry that you have these problems :)
Did you change something with your config? I have tried it with your [Trainconfig.csv](https://github.com/DerJantob/TSW2_Controller/files/8326945/Trainconfig.csv) and [user.zip](https://github.com/DerJantob/TSW2_Controller/files/8358156/user.zip), set my keyboard layout to US, but didn't experience this issue?

Kind regards,
Jannik

**Comment by danbaz101** [comment]
Thanks!

I have not changed anything.

Is it correct that if I set Increase Brake and Decrease Brake and I press ; that it finds the a umlaut and when I press ' it finds u umlaut? See snip. I had expected it would show my ; and '
![image](https://user-images.githubusercontent.com/83304085/162624954-12711863-ee0e-4874-af5a-c2df81d3a15b.png)

Kind regards,

Daniel

**Comment by DerJantob** [comment]
In version 1.0.4 it is correct that it shows äöü or something else. In version 1.1.0 it will be changed to oem1, oem2, ... , to prevent confusion. Since I don't really have experience with programming different keyboard layouts, I haven't managed to get the correct character to be displayed yet.
But for now I'll see how I can fix your problem.

**Comment by DerJantob** [comment]
Do you still have "Bremse nach Umgehung drücken" deleted from the buttons of BR403/406? If your joystick 0 JoyY is inaccurate and the number jumps around, it sometimes presses your brake back down again. This looks similar to your problem.

**Comment by danbaz101** [comment]
Will check now

**Comment by danbaz101** [comment]
I have this  line in my config.
Will delete and try again now.

**Comment by danbaz101** [comment]
This was the problem.
It worked right away now.
Thank you very much!

I deleted that whole line from the config file.

**Comment by DerJantob** [comment]
I'm glad I could help you!
