### ISSUE TITLE
Program freezing / stuttering

### ISSUE THREAD

**Issue by tgross03** [DerJantob/TSW2_Controller#30]
Hi,

I discovered your program today and tried to use it with my Thrustmaster Hotas Warthog Throttle and
a pedal I am using. 
The basic functions did work but the program keeps not responding from time to time
and it freezes while I try to play.

What reason could this have?

Best regards

Tom

**Comment by DerJantob** [comment]
Hm, this of course should not be happening.
One possibility is that your PC may be overloaded. What is your CPU load like during this problem?
Are you using Windows 10 or 11?
Does this problem only occur when TSW2 is running at the same time, or does it also occur when the program is running alone?

Kind regards,
Jannik

**Comment by tgross03** [comment]
My CPU is below 20% load while TSW2 and the Controller are running and it is relatively new and the Task-Manager shows no particularly high load on any component while playing and using the Controller.
I am using Windows 10 and the problem occurs both when TSW2 is running and when it is not.

Best regards
Tom

**Comment by DerJantob** [comment]
Does this also occur when "Active" is not checked?

**Comment by tgross03** [comment]
Yes, it does.

**Comment by DerJantob** [comment]
I changed something. Do you still have this problem in this version? [TSW2_Controller_PreRelease_1_1.1.2.zip](https://github.com/DerJantob/TSW2_Controller/files/8592403/TSW2_Controller_PreRelease_1_1.1.2.zip)

**Comment by tgross03** [comment]
Seems so, thanks for the fast and friendly support :)

**Comment by DerJantob** [comment]
No problem! I suspect that this was due to the automatic detection of joysticks. Probably there was a timeout problem with one of your joysticks or something.
Let me know if the problem occurs again.

Kind regards,
Jannik
