### ISSUE TITLE
TSW2 Controller crashes

### ISSUE THREAD

**Issue by danbaz101** [DerJantob/TSW2_Controller#31]
Hi Jannik,

I have installed version 1.1.1 (latest) and have not made any changes myself. Now your app crashes ater a few minutes and before that it does not behave as smooth as it did before.

I am on Windows 10 - fully updated.

Hope you can help.

Kind regards,

Daniel

**Comment by danbaz101** [comment]
And what is the process to go back to a previous install?
Run previous version installer or uninstall the app completely first?

**Comment by DerJantob** [comment]
Do you get an error message when the program crashes, and can you maybe send me the log file of the crash?
(./Local/TSW2_Controller/Log)

To go back to an older version, you should be able to just run the older installer. Maybe you should save your config in advance.

Kind regards,
Jannik

**Comment by danbaz101** [comment]
Here are the three log files.
No warning, joystick becomes unresponsive. Then trying to de-activate and see spinning wheel. Have to force close the app to get out of it.

[log20220430_14_14_04.txt](https://github.com/DerJantob/TSW2_Controller/files/8597049/log20220430_14_14_04.txt)
[log20220430_14_21_16.txt](https://github.com/DerJantob/TSW2_Controller/files/8597050/log20220430_14_21_16.txt)
[log20220430_14_13_41.txt](https://github.com/DerJantob/TSW2_Controller/files/8597051/log20220430_14_13_41.txt)

Will try to go back to previous for now.

Kind regards,

Daniel

**Comment by DerJantob** [comment]
Ok, thank you. I will try to fix this bug.

**Comment by DerJantob** [comment]
I have released version 1.1.2. Let me if your problem still occurs.

**Comment by danbaz101** [comment]
Thanks. Will look at it when I can and let you know.

**Comment by danbaz101** [comment]
Hi Jannik, I have done two succesful runs yesterday (BR422 and BR403). All seems fine, but it felt as if the levers response was a bit more sluggish to previous version. Perhaps it is nothing, but thought to mention it.

**Comment by DerJantob** [comment]
I'll have to take a closer look at that. I'm currently working on changing quite a bit, though I have to admit that I haven't felt like moving on lately. Maybe I will continue working on it in the days.

Kind regards
Jannik

**Comment by danbaz101** [comment]
All good Jannik,
I am not driving a lot nowadays. Too busy with other stuff.
You can close this topic if you like and then when a new version comes out and I have time to play with it, I will let you know how it goes.

Kind regards,

Daniel
