### ISSUE TITLE
Possible system resources waste related to Tesseract OCR

### ISSUE THREAD

**Issue by asdf1280** [DerJantob/TSW2_Controller#37]
```c#
        public static string GetText(Bitmap imgsource)
        {
            var ocrtext = string.Empty;
            using (var engine = new TesseractEngine(@"./tessdata", "deu", EngineMode.Default))
            {
                //engine.SetVariable("load_system_dawg", true);
                //engine.SetVariable("language_model_penalty_non_dict_word", 1);
                //engine.SetVariable("language_model_penalty_non_freq_dict_word", 1);
                using (var img = PixConverter.ToPix(imgsource))
                {
                    using (var page = engine.Process(img))
                    {
                        ocrtext = page.GetText();
                    }
                }
            }
            ocrtext = ocrtext.Replace(",", ".");
            return ocrtext;
        }
```

The TesseractEngine is initialized every time the function is run. TesseractEngine class prepares for every operation related to screen reading and it wouldn't be appropriate to initialize it every time. Consider initializing TesseractEngine on startup and saving it as a class member variable.

**Comment by DerJantob** [comment]
![grafik](https://user-images.githubusercontent.com/79801484/171910723-9879e629-be44-49dd-81c0-bd8e5e2a8334.png)
True, that would really be a way to speed up text recognition. I measured the time and it took 381ms to initialize Tesseract.
I have to see how I implement your suggestion

**Comment by DerJantob** [comment]
I have changed it in the "Tesseract_improvement" branch and I must say it is a big improvement in speed. The recognition is much faster now. Thank you for pointing it out!

**Comment by DerJantob** [comment]
Is it ok if I mention your username in the changelog for this improvement?

**Comment by asdf1280** [comment]
fine
