### ISSUE TITLE
Issue with 3840x1080 resolution.

### ISSUE THREAD

**Issue by fablam77** [DerJantob/TSW2_Controller#43]
Hi,
I have an issue using the resolution 3840x1080. I'm unable to have it working in this resolution. If I set 1920x1080, I'm able to set my joystick.
Also, after switching to 1920x1080, the 3840x1080 in the soft is not available anymore. I have to reinstall to see it again... 

Thanks,
Fabrice

**Comment by DerJantob** [comment]
I think you mean that you have to re-enter the resolution and not reinstall the program, right?
If so, I can fix this in the new version.

**Comment by fablam77** [comment]
Yes, sorry, I did not notice that I could enter my resolution...
I also made some tests in 2560x1080. Working better than in 3840x1080, but throttle is slowly going down... (I made my tests with throttle setup only).

**Comment by DerJantob** [comment]
If the throttle is slowly going down, it means that the program could not read the current position of the controller in tsw2. You can check the readings if you activate "Debug information" and "Show screenshot".

**Comment by fablam77** [comment]
Right, this is the issue. Log shows "No text for thtottle found". And the screenshots are showing an area close to the center of the screen...
Actually it looks like the horizontal offset from the left of the screen is still set for a 1920 resolution and does not adapt to the 2560 or 3840 resolution...

**Comment by DerJantob** [comment]
Do you have a widescreen monitor?

**Comment by fablam77** [comment]
Yes, 49", native resolution 3840x1080.

**Comment by DerJantob** [comment]
In the windows settings, is the widescreen monitor also your main screen?

![grafik](https://user-images.githubusercontent.com/79801484/180307634-53fa514c-3b9b-4858-b7ec-8326453666c6.png)

**Comment by fablam77** [comment]
Yes, I have one monitor only.

**Comment by DerJantob** [comment]
Is the program showing the right resolution on the main screen?
![grafik](https://user-images.githubusercontent.com/79801484/180311220-5871388d-c5fc-450d-abb2-ab143e049e46.png)

If so, could you send me your helpfile? Maybe this can resolve the problem.
Settings->Help->Create helpfile

**Comment by fablam77** [comment]
Yes.
![capture](https://user-images.githubusercontent.com/109661409/180475160-dc66dd1e-a8b0-4ee9-a1f7-97e17e2b6092.png)

Here is the help file:
[TSW2Controller_HelpFile.zip](https://github.com/DerJantob/TSW2_Controller/files/9169068/TSW2Controller_HelpFile.zip)

**Comment by DerJantob** [comment]
I haven't found a log file where you test the 3840x1080 resolution (probably it was deleted automatically). If you have time, maybe you could test the program again in tsw and send me the new log file.
So far everything is working for me. I have set my 16/9 monitor to 3840x1080 and as it looks, it seems to work with the program.

I know these are stupid questions, but are you actually using the 3840x1080 resolution in tsw2?

**Comment by fablam77** [comment]
I'm usually using 2560x1080 because of the distortion in 3840. When I tried your software, it proposed automatically 3840x1080, and as I didn't know I could add a resolution, I setup the game in 3840x1080. 
However, I  have the issue in both 3840 and 2560 resolutions. It's only working in 1920x1080.

Deleted all logs and did a short test in 3840, here is the helpfile.
[TSW2Controller_HelpFile.zip](https://github.com/DerJantob/TSW2_Controller/files/9170384/TSW2Controller_HelpFile.zip)

Let me know if you would like a  file in 2560.
Thanks.

**Comment by DerJantob** [comment]
But you also made sure that the HUD is active in the game, right?

If so, could you please record a video like my example? Try to find the top left corner of the screenshot the program takes. The program that shows the coordinates is this one:
[Program.zip](https://github.com/DerJantob/TSW2_Controller/files/9172402/Program.zip)
I know this is kind of complicated, but a video would help me a lot.

https://user-images.githubusercontent.com/79801484/180575040-4b16f7f5-0afd-43f0-a856-6d379fa06108.mp4

**Comment by fablam77** [comment]
Yes, HUD is on.
I made two videos. One for 2560x1080 and one for 3840x1080. They are too big to be uploaded here, so I put them on Youtube... But for some reason, they are blurry...
2560: https://youtu.be/KxJ8dBUSbGs 
3840:  https://youtu.be/LfueDTHGzrw 

Here are screenshots in case the quality is not good enough:
![image](https://user-images.githubusercontent.com/109661409/180599318-7835f5d9-b709-4dec-998b-ada6feeb1abb.png)
![image](https://user-images.githubusercontent.com/109661409/180599387-dc66aefb-30f5-42e2-84a2-73a93a9a76ba.png)

**Comment by fablam77** [comment]
I used your tool to see the text position in game. 
In 2560 it's at 1920x540.
In 3840, it's at 3640x356.

so in 2560, there is a vertical offset with your soft, but in 3840, it's an horizontal offset...
What I find strange is that despite having the same vertical resolution, the vertical position of the text in the game is different...

**Comment by DerJantob** [comment]
I think I **might** found the problem.
Please go to the TSW2_Controller.exe file and replace it with the new .exe and try it out in TSW2. (You can find your .exe file by right-clicking your shortcut on the desktop and then clicking on "open file location")
[TSW2_fix.zip](https://github.com/DerJantob/TSW2_Controller/files/9173736/TSW2_fix.zip)

If it doesn't work, you can undo it with this file:
[Undo.zip](https://github.com/DerJantob/TSW2_Controller/files/9173738/Undo.zip)

**Comment by fablam77** [comment]
Yes! YES! it's working in both 2560 and 3840.
Thank you so much. Fantastic support!

**Comment by DerJantob** [comment]
> In 2560 it's at 1920x540.
> In 3840, it's at 3640x356.


I'm glad I could help, but this is still a little weird. So it is possible that it does not run perfectly yet. If you encounter any further problems, please feel free to contact me again.

**Comment by fablam77** [comment]
I will. Thanks a lot.

**Comment by DerJantob** [comment]
No problem!
