### ISSUE TITLE
Button functionality with hotkeys

### ISSUE THREAD

**Issue by tgross03** [DerJantob/TSW2_Controller#48]
Hey there,

I wanted to create a button assignment for my Thrustmaster Hotas Warthog and I
used Button 7 and 3 to create a PZB assignment. But the different options don't really make
sense to me.

I just want it to press the hotkeys (ALT+3 and ALT+2) while I press the assigned button but none of the options seem
to fulfill that. 
I tried "Short press" for ALT and the specific number with 0 ms and 10 ms waiting time and I tried "Hold down" for
about 300 ms and I tried a combination of "Press down" and the "Release" with a delay between them but none worked for me.

What option would you suggest for that task and what did I possibly misunderstand about the different functions?

Greetings,

Tom

**Comment by DerJantob** [comment]
I have explained this in my tutorial [here.](https://youtu.be/Sej1L0p_myo?t=1548)
In my example, I have created the key shortcut CTRL+5. Maybe this will help you.

Regards
Jannik

**Comment by DerJantob** [comment]
Hey, just wanna know if your issue has been resolved.

Regards
Jannik
