### ISSUE TITLE
AFB lever using joystick axis

### ISSUE THREAD

**Issue by davidpsc** [DerJantob/TSW2_Controller#49]
Hi!

First of all, thank you very much for this great program! I switched from Raildriver to a better joystick (in regards to axis input smoothness) and sadly TSW doesn't support general joysticks and so I use your program.

For throttle and brake everything works fine (if you don't forget to click Save for every axis that you configure...) but I also want to control the AFB via axis input. I tried to set it up using steps but it didn't work correctly. So I switched to "continuously variable" and it seems to work quite well except that the "AFB 100 km/h" message always pops up in TSW even when the joystick axis is not moved. Sometimes it also jumps between 3 steps continuously until I slightly move the axis. I also think that it can't interpret the value correctly because if I move the AFB lever in-game and then move the joystick axis it doesn't move to the desired position (it just moves an amount of time).

Config for AFB:
`BR146,,AFB,0,JoyZ,-100|100|100|0,,[0|3=0][3|6=10][6|9=15][9|13=20][13|16=25][16|19=30][19|22=35][22|25=40][25|28=45][28|31=50][31|34=55][34|38=60][38|41=65][41|44=70][44|47=75][47|50=80][50|53=85][53|56=90][56|59=95][59|63=100][63|66=105][66|69=110][69|72=115][72|75=120][75|78=125][78|81=130][81|84=135][84|88=140][88|91=145][91|94=150][94|97=155][97|100=160],,,Stufenlos,31,,35,[0|10=1000][10|0=1000]`

My axis (raw value) goes from 100 (= off) to -100 (= max).

Could you help me to set it up correctly so it works as expected? Thank you very much in advance!

Grüße, David
(Wenn es leichter zu erklären ist, gerne auch auf Deutsch antworten. Ich hab es auf Englisch geschrieben, da Englisch mehr Leute verstehen, falls sie das gleiche Problem haben)

**Comment by DerJantob** [comment]
I haven't done anything to the program in a while, but I think the problem is the "km/h".
You could go into settings and activate debug information. Then you can watch what the program is doing. It would help if you send me the helpfile (Settings->Help->Create helpfile). There I can look at the logs and your whole configuration.

**Comment by davidpsc** [comment]
Thanks for the quick response! Please find attached the helpfile zip. Your guess was right, regarding to the logfile it can't parse the number because of "km/h". Maybe you can adjust the program to extract all numeric information and ignore every (suffixed) text? It also seems that "O" should be mapped to "0" so it works correctly.

Thank you very much for your help!

[TSW2Controller_HelpFile.zip](https://github.com/DerJantob/TSW2_Controller/files/10613863/TSW2Controller_HelpFile.zip)

**Comment by DerJantob** [comment]
I will check in the coming days how I can best solve this. I have actually tried to simply isolate the numbers, but that resulted in the program often detecting completely incorrect positions.

**Comment by davidpsc** [comment]
Hi!

I tried to temporarly work around this problem by using the special case conversion (0 km/h=0, 10 km/h=10, ...) and it does work quite well. But the long press seems to be too short. AFB activation  and deactivation (0 --> 10 / 10 --> 0) requires a keypress of about 1 sec (or even longer). I now configured 2 sec (2000 ms) but it doesn't hold down the key long enough.

My config for AFB now:
`BR146,,AFB,1,JoyZ,-100|100|100|0,,[0|3=0][3|6=10][6|9=15][9|13=20][13|16=25][16|19=30][19|22=35][22|25=40][25|28=45][28|31=50][31|34=55][34|38=60][38|41=65][41|44=70][44|47=75][47|50=80][50|53=85][53|56=90][56|59=95][59|63=100][63|66=105][66|69=110][69|72=115][72|75=120][75|78=125][78|81=130][81|84=135][84|88=140][88|91=145][91|94=150][94|97=155][97|100=160],,,Stufenlos,31,[Okm/h=0][O km/h=0][0km/h=0][0 km/h=0][10km/h=10][10 km/h=10][15km/h=15][15 km/h=15][20km/h=20][20 km/h=20][25km/h=25][25 km/h=25][30km/h=30][30 km/h=30][35km/h=35][35 km/h=35][40km/h=40][40 km/h=40][45km/h=45][45 km/h=45][50km/h=50][50 km/h=50][55km/h=55][55 km/h=55][60km/h=60][60 km/h=60][65km/h=65][65km/h=65][70 km/h=70][70km/h=70][75 km/h=75][75km/h=75][80 km/h=80][80km/h=80][85 km/h=85][85km/h=85][90 km/h=90][90km/h=90][95 km/h=95][95km/h=95][100 km/h=100][100km/h=100][105 km/h=105][105km/h=105][110 km/h=110][110km/h=110][115 km/h=115][115km/h=115][120 km/h=120][120km/h=120][125 km/h=125][125km/h=125][130km/h=130][130 km/h=130][135km/h=135][135 km/h=135][140km/h=140][140 km/h=140][145km/h=145][145 km/h=145][150km/h=150][150 km/h=150][155km/h=155][155 km/h=155][160km/h=160][160 km/h=160],37,[0|10=2000][10|0=2000]`

Maybe the program cannot hold down the key long enough because of the timer interval?

**Comment by DerJantob** [comment]
Hey!
I have revised the program and decided to turn on the isolating method again. I can't quite remember where the problems originated, but I've made a few other changes and I think it should work better now. You just need to replace the TSW2_Controller.exe with the exe inside of [TSW2_Controller_PreRelease_1.zip](https://github.com/DerJantob/TSW2_Controller/files/10700634/TSW2_Controller_PreRelease_1.zip) and your first configuration should work correctly.

The problem with the long press is only due to the fact that you used "=" instead of ":". I have made a change, so when creating a configuration, both should work.
I have also made other small changes. For example, when switching between controllers, you will be asked if you would like to save before switching :)

It would be great if you could test it out and let me know if it works as intended or if there still are problems. 

Regards, Jannik

**Comment by davidpsc** [comment]
That sounds great! I'll try it as soon as possible (this will probably be on Sunday) an let you know how it works.

Thank you very much!

**Comment by davidpsc** [comment]
Hi!
It now works correctly for the AFB, just for 0 km/h it still recognizes the 0 as O and therefore I need to enter `Okm/h=0` as a special case but besides that the long press and number recognization now work as expected :)

Just two tiny things (not related to the AFB):
- "Back" button doesn't work anymore (when configuring axis/buttons for a loco)
- It would be nice if the selected loco/train in the main window is also selected when opening settings and clicking the "Controls" button. Vice versa the configured loco (or previously selected loco) should be still selected when coming back to the main window after configuration

Maybe you can put this improvements on your list to fix it as soon as you work on the program again.

Thank you!
Regards, David

**Comment by DerJantob** [comment]
I have now fixed the back button (I should have noticed that haha).
Your suggestion with the dropdown menu was not so easy to implement, but it should work now. You can try it out and let me know if it works as expected. It would be very nice, if you tried it out a bit to see if everything works correctly ^^
[TSW2_Controller_PreRelease_2.zip](https://github.com/DerJantob/TSW2_Controller/files/10716212/TSW2_Controller_PreRelease_2.zip)


Regards,
Jannik

**Comment by davidpsc** [comment]
Thank you very much for the fast fix and implementation!
I played around with the buttons and menus a bit and everything seems to work fine except for a very small thing: if you create a new loco config, the loco isn't automatically selected in the main window ;)

Regards, David

**Comment by DerJantob** [comment]
I have fixed this little issue and released v2.0.4
Thank you for your suggestion and for testing!

Regards,
Jannik
