### ISSUE TITLE
BR 403 - Brake lever - Bypass

### ISSUE THREAD

**Issue by danbaz101** [DerJantob/TSW2_Controller#55]
Hi Jannik,

The Brake in BR403 as in other trains has 9 notches and a spring loaded bypass.
I would like to use the Controller as a button option to trigger the bypass as follows: <-95 --> hold  oem1 key for 1 second.
This works if the joystick is not used to also control the brakes, but the combination I did not get to work.

The brake lever goes from -100 to 100.
This is how I would like to assign:
Controller: -100 to -90 no assignment
Controller: -90 to 100 used for the 9 notches
Controller as a Button: <95 hold  oem1 key for 1 second

When I set -90 = 0 and 100 = 100, then between -100 and -90 the program sees this as 100 and goes to full brake application.
Ideally it would see this as undefined and does nothing so the Controller as a Button can work.
I hope I explained it well enough..

Kind regards,

Daniel

**Comment by DerJantob** [comment]
I think I understand what you mean. 
You should be able to fix the problem if you press the "edit" button and adjust the value as I did.
![grafik](https://github.com/DerJantob/TSW2_Controller/assets/79801484/9e3a0f48-9a7a-4110-aefd-a6cc5012102d)

Here is why:
If you say that -90=100, the program assumes that -90 is the maximum of your joystick. All values below -90 are continued linearly (see red line). But if you then say that -100 also equals 100, then the program knows that all values between point A and B must still be 100.

X-axis=Joystick value
Y-axis=Converted value
![grafik](https://github.com/DerJantob/TSW2_Controller/assets/79801484/ee79cf79-ac1d-4585-902b-1fbf1f873179)
![grafik](https://github.com/DerJantob/TSW2_Controller/assets/79801484/d98b1fcd-8195-4c74-93cd-0ffd35a8ec2d)

I hope that was understandable and fixes your problem.

Regards
Jannik

**Comment by danbaz101** [comment]
Thanks for explanation!

I needed it inverted so did it like this.
However, when pushing lever below -95 still no button kicked in.
Earlier when my lever between -100 and 0 was not detected it worked, hence I guess that if we can make -100 to -90 as undefined, then it would work, or perhaps this is a  hierarchy thing where detected lever range overrules controller as button?

![image](https://github.com/DerJantob/TSW2_Controller/assets/83304085/3476f789-3e63-48f3-b00e-86a14412073b)

**Comment by DerJantob** [comment]
Woops, don't know how this bug has been undiscovered since probably v2.0.0. ^^
Please try out this version:
[TSW2_Controller_PreRelease_2.zip](https://github.com/DerJantob/TSW2_Controller/files/11584706/TSW2_Controller_PreRelease_2.zip)

**Comment by danbaz101** [comment]
Haha. 
I appreciate all your help today! It works great now. :)

**Comment by DerJantob** [comment]
Great to hear! I will try to do some more improvements and will release it as an update.
Thank you for helping!
