### ISSUE TITLE
Read key config from game

### ISSUE THREAD

**Issue by Bluscream** [DerJantob/TSW2_Controller#61]
It would be nice if the app could read the `Documents\My Games\TrainSimWorld4\Saved\Config\WinGDK\Input.ini` file and apply the mappings from there, so the app can still convert the joystick inputs even if the keys for increasing/decreasing thrust have been changed.

**Comment by DerJantob** [comment]
Hey, 
First of all, sorry for the late response.
I generally like the idea, but I think the implementation might be challenging.
Dovetail Games has generally not made it easy for me over the course of time, by e.g. changing visuals, each train text being different and so on. So I don't really want to rely on their ini file.
Also, I am not so sure that all versions (Epic/Steam/Microsoft Store/...) have the same layout. (In my case, the folder "WinGDK" doesn't even exist :) )

I think the implementation would be too much of a hassle for me, so I don't think I will make any changes.
But still, thank you very much for your suggestion!

Regards
Jannik

**Comment by Bluscream** [comment]
Whats the recommended way to adjust the settings of your tool to match changed bindings then? Havent seen a keybind changer in your settings

**Comment by DerJantob** [comment]
Go to Settings -> Controls -> Global keybinds
There you can set the bindings for each controller manually.
