### ISSUE TITLE
Compatible with TSW5?

### ISSUE THREAD

**Issue by fablam77** [DerJantob/TSW2_Controller#63]
Hi Jannik,

I've been away from TSW since TSW3, and was loving using your tool. Now, I'm looking to maybe purchase TSW5 and come back to train simulation. I see your tool is TSW4 compatible, but cannot find anything about TSW5.
As it is out of question for me to use TSW5 without your tool, could you please tell me if it is compatible, or, if not, if you plan to make it compatible in a near future?

Thanks a lot,
Fabrice

**Comment by DerJantob** [comment]
Hey Fabrice,

Yes, the program is also TSW5 compatible, as nothing has really changed in the mechanics. I just forgot about adding this information to GitHub :)

Regards
Jannik

**Comment by fablam77** [comment]
Great news! Thanks a lot Jannik.Le 31 oct. 2024 à 18:35, DerJantob ***@***.***> a écrit :﻿
Hey Fabrice,
Yes, the program is also TSW5 compatible, as nothing has really changed in the mechanics. I just forgot about adding this information to GitHub :)
Regards
Jannik
